### PR TITLE
Initial commit for adding descriptions to top level commands

### PR DESCRIPTION
**Pull request by aileronajay**

### CODE REVIEW

**Comment by lodejard** [comment]
Hi @aileronajay, thanks for looking at this! Sorry I was swamped yesterday. I'll reply back today sometime with some recommendations for text

**Comment by lodejard** [comment]
So let's see...

* account: Manages authentication credentials
* account add: Stores authentication credentials to be used by non-interactive deploy
* account show: Displays the credentials have been stored
* account clear: Remove any authentication credentials which have been stored
* deploy: Processes a workflow and executes the operations
* generate: Processes a workflow without executing any operations
* help: Show help information

**Comment by aileronajay** [comment]
@lodejard I have updated the descriptions

**Comment by lodejard** [comment]
Merged - Thanks again for the contribution!

**Pull request merged**
